<a href="https://colab.research.google.com/github/SamanthaNoelleDaluz/LinearAlgebra_2ndSem/blob/main/Assignment_5_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

## Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

The transpose of a matrix is obtained by transferring the data from the rows to the columns and the data from the columns to the rows. If we have an array of shape (X, Y), the array's transposition will have the same shape (Y, X).

$$A = \begin{bmatrix} 1 & 2 & 3\\4 & 5 &6 \\ 7 & 8 & 9\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 4 & 7\\2 & 5 & 8 \\ 3 & 6 & 9\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [3]:
A = np.array([
    [1 ,2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
AT1 = np.transpose(A)
AT1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
AT2 = A.T
AT2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4,0],
    [5,6,7,8,0],
])
B.shape

(2, 5)

In [ ]:
np.transpose(B).shape

(5, 2)

In [ ]:
B.T.shape

(5, 2)

## Dot Product / Inner Product

This function returns the dot product of two arrays. It's the same as matrix multiplication for 2-D vectors. It is the inner product of the vectors for 1-D arrays. It is a sum-product over the last axis of a and the second-last axis of b for N-dimensional arrays.

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
A = np.array([
    [3,4,6],
    [6,7,9]
])
B = np.array([
    [-6,3,5],
    [1,7,9]
])

In [ ]:
np.dot(X,Y)

array([[-14,  37],
       [-29,  67]])

In [ ]:
X.dot(Y)

array([[-14,  37],
       [-29,  67]])

In [ ]:
X @ Y

array([[-14,  37],
       [-29,  67]])

In [ ]:
np.matmul(X,Y)

array([[-14,  37],
       [-29,  67]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The two matrices in question must have the same inner dimensions.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4&3\\5&-2&6\\0&1&8\end{bmatrix}, 
B = \begin{bmatrix}1&1&7\\3&3&6\\-1&-2&4\\4&8&9\end{bmatrix}, 
C = \begin{bmatrix}1&1\\9&2\\7&3\end{bmatrix}$$

So in this case $A$ has a shape of $(3,3)$, $B$ has a shape of $(3,4)$ and $C$ has a shape of $(2,2)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot A$.  

In [ ]:
S = np.array([
    [2, 4,3],
    [5, -2,6],
    [0, 1,8]
])
A = np.array([
    [1,1,7],
    [3,3,6],
    [-1,-2,4],
    [4,8,9]
])
M = np.array([
    [1,1],
    [9,2],
    [7,3]
])
print(S.shape)
print(A.shape)
print(M.shape)

(3, 3)
(4, 3)
(3, 2)


In [ ]:
S @ M

array([[59, 19],
       [29, 19],
       [65, 26]])

In [ ]:
A @ S

array([[  7,   9,  65],
       [ 21,  12,  75],
       [-12,   4,  17],
       [ 48,   9, 132]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[ 24,  85],
       [ 30, 136]])

In [ ]:
X = np.array([
    [1,2,3,4,0]
])
Y = np.array([
    [5,6,7,8,9]
])
print(X.shape)
print(Y.shape)

(1, 5)
(1, 5)


In [ ]:
Y.T @ X

array([[ 5, 10, 15, 20,  0],
       [ 6, 12, 18, 24,  0],
       [ 7, 14, 21, 28,  0],
       [ 8, 16, 24, 32,  0],
       [ 9, 18, 27, 36,  0]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

Dot product in matrix refers to the summation of all products of each entry. It is composed of 6 unique properties.
* The first property proves that the dot product of A and B is not equal to the dot product of B and A. This also means that the commutative property of multiplication is not applicable to matrices.
* The second property shows that the product of A and dot product of B and C is equal to the product of C and dot product of A and B. This shows the associative property of multiplication.
* The third property of the dot product of matrices shows that the A multiplied by the sum of B and C is equal to the sum of the product of A and B and product of A and C. This presents the distributive property of multiplication. 
* The fourth property is somehow similar to the third property, where A is distributed to both B and C. It is equal to the sum of the product of B and A, and the product of C and A. 
* The fifth property shows that when A is  multiplied by I the products will always be A, regardless of the order in which multiplication was performed. This shows the multiplicative identity property.
* The last property shows that any matrix multiplied by zero the product will always be equal to zero. This shows the multiplicative property of zero.



In [ ]:
A = np.array([
    [3,2,1],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [3,2,4],
    [5,1,1],
    [1,2,8]
])
C = np.array([
    [1,0,0],
    [1,1,0],
    [0,1,1]
])

In [ ]:
A.dot(np.ones(A.shape))

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [ ]:
z_mat = np.array(B.shape)
z_mat

array([3, 3])

In [ ]:
a_dot_z = B.dot(np.ones(A.shape))
a_dot_z

array([[ 9.,  9.,  9.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

False

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[ 9.  9.  9.]
 [ 7.  7.  7.]
 [11. 11. 11.]]


True

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
A = np.array ([
    [1,2,3,4],
    [5,6,7,8],
    [9,1,2,3],
    [4,5,6,7]           
])
B = np.array ([
    [0,0,0,1],
    [0,0,6,5],
    [0,2,1,9],
    [7,6,5,4]           
])
C = np.array ([
    [4,3,2,1],
    [8,7,6,5],
    [3,2,1,9],
    [7,6,5,4]           
])

In [4]:
D = A.dot(B)
E = A.dot(C)
F = B.dot(C)
G = B + C
H = D + E
I = B.dot(A)
J = C.dot(A)
K = I + J

In [8]:
np.array_equiv(D, I)

False

In [10]:
np.array_equiv(A.dot(F),D.dot(C))

True

In [11]:
np.array_equiv(A.dot(G),H)

True

In [ ]:
np.array_equiv(G.dot(A),K)

True

In [ ]:
A.dot(1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
A.dot(0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Determinant

The determinant is a special number that can be calculated from a matrix. It has to be a square matrix in order to proceed. Cross multiplication is the process to perform determinant in matrix.


The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [1,5,8],
    [0,2,4],
    [1,3,3]
])
np.linalg.det(A)

-2.0

In [ ]:
B = np.array([
    [0,3,5,6,9],
    [0,0,1,3,0],
    [3,1,0,2,7],
    [5,2,6,0,3],
    [1,2,2,7,0]
])
np.linalg.det(B)

1806.0000000000018

In [ ]:
C = np.array([
    [1,4],
    [2,1]
])
np.linalg.det(C)

-7.000000000000001

## Inverse

Inverse of a Matrix is one of the matrix where multiplying the given matrix, which shows multiplicative identity. It is denoted as A^-1.


The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [2,3],
    [1,-1]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
S=np.array([
    [1,2,3],
    [3,4,5],
    [6,9,0]
])
A = np.linalg.inv(S)
A

array([[-1.875     ,  1.125     , -0.08333333],
       [ 1.25      , -0.75      ,  0.16666667],
       [ 0.125     ,  0.125     , -0.08333333]])

In [ ]:
S @ A

array([[ 1.00000000e+00,  0.00000000e+00,  6.93889390e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.75, 0.25],
    [0.75, 2.0, 1.50],
    [3.0, 2.25, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [1.45],
       [1.65]])

# Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [36]:
A = np.array ([
    [1,2,3,4],
    [5,6,7,8],
    [9,1,2,3],
    [4,5,6,7]           
])
B = np.array ([
    [0,0,0,1],
    [0,0,6,5],
    [0,2,1,9],
    [7,6,5,4]           
])
C = np.array ([
    [4,3,2,1],
    [8,7,6,5],
    [3,2,1,9],
    [7,6,5,4]           
])

In [57]:
D = A.dot(B)
E = A.dot(C)
F = B.dot(C)
G = B + C
H = D + E
I = B.dot(A)
J = C.dot(A)
K = I + J

In [46]:
print('PROPERTY NO. 1')
print(f'Is AB=BA?:  {np.array_equiv(D, I)}')
print('Matrix AB:')
print(np.matmul(A,B))
print(f'Shape:\t{np.matmul(A,B).shape}')
print('Matrix BA:')
print(np.matmul(B,A))
print(f'Shape:\t{np.matmul(B,A).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 1
Is AB=BA?:  False
Matrix AB:
[[ 28  30  35  54]
 [ 56  62  83 130]
 [ 21  22  23  44]
 [ 49  54  71 111]]
Shape:	(4, 4)
Matrix BA:
[[  4   5   6   7]
 [ 74  31  42  53]
 [ 55  58  70  82]
 [ 98  75  97 119]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [47]:
print('PROPERTY NO. 2')
print(f'Is A(BC)=(AB)C?:  {np.array_equiv(A.dot(F),D.dot(C))}')
print('Matrix A(BC):')
print(np.matmul(A,F))
print(f'Shape:\t{np.matmul(A,F).shape}')
print('Matrix (AB)C:')
print(np.matmul(D,C))
print(f'Shape:\t{np.matmul(D,C).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 2
Is A(BC)=(AB)C?:  True
Matrix A(BC):
[[ 835  688  541  709]
 [1879 1548 1217 1633]
 [ 637  527  417  514]
 [1618 1333 1048 1402]]
Shape:	(4, 4)
Matrix (AB)C:
[[ 835  688  541  709]
 [1879 1548 1217 1633]
 [ 637  527  417  514]
 [1618 1333 1048 1402]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [52]:
print('PROPERTY NO. 3')
print(f'Is A(B+C)=(AB)+(AC)?:  {np.array_equiv(A.dot(G),H)}')
print('Matrix A(B+C):')
print(np.matmul(A,G))
print(f'Shape:\t{np.matmul(A,G).shape}')
print('Matrix (AB)+(AC):')
print(np.add(D,E))
print(f'Shape:\t{np.add(D,E).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 3
Is A(B+C)=(AB)+(AC)?:  True
Matrix A(B+C):
[[ 85  77  72 108]
 [201 181 176 260]
 [ 92  78  64  88]
 [172 155 150 222]]
Shape:	(4, 4)
Matrix (AB)+(AC):
[[ 85  77  72 108]
 [201 181 176 260]
 [ 92  78  64  88]
 [172 155 150 222]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [55]:
print('PROPERTY NO. 4')
print(f'Is (B+C)A=(BA)+(CA)?:  {np.array_equiv(G.dot(A),K)}')
print('Matrix (B+C)A:')
print(np.matmul(G,A))
print(f'Shape:\t{np.matmul(G,A).shape}')
print('Matrix (BA)+(CA):')
print(np.add(I,J))
print(f'Shape:\t{np.add(I,J).shape}')
print('PROPERTY PROVEN!')


PROPERTY NO. 4
Is (B+C)A=(BA)+(CA)?:  True
Matrix (B+C)A:
[[ 45  38  49  60]
 [191 120 157 194]
 [113 122 149 176]
 [196 150 194 238]]
Shape:	(4, 4)
Matrix (BA)+(CA):
[[ 45  38  49  60]
 [191 120 157 194]
 [113 122 149 176]
 [196 150 194 238]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [65]:
print('PROPERTY NO. 5')
print(f'Is A(1)=A?:  {np.array_equiv(A.dot(1),A)}')
print('Matrix A(1):')
print(np.multiply(A,1))
print(f'Shape:\t{np.multiply(A,1).shape}')
print('Matrix A:')
print(A)
print(f'Shape:\t{A.shape}')
print('PROPERTY PROVEN!')


PROPERTY NO. 5
Is A(1)=A?:  True
Matrix A(1):
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]
Shape:	(4, 4)
Matrix A:
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [67]:
print('PROPERTY NO. 6')
print(f'Is A(0)=0?:  {np.array_equiv(A.dot(0),0)}')
print('Matrix A(0):')
print(np.multiply(A,0))
print(f'Shape:\t{np.multiply(A,0).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 6
Is A(0)=0?:  True
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape:	(4, 4)
PROPERTY PROVEN!
